import base64
import os
import shutil
import tempfile
import time
import unittest
import uuid
from pathlib import Path
from types import SimpleNamespace
from unittest.mock import patch

import psycopg2

from core.attachments import AttachmentService
from core.database import Database, load_server_config


class TestClientAttachmentsIntegration(unittest.TestCase):
    """Exercise the real PostgreSQL ownership query and rendered client panel."""

    @classmethod
    def setUpClass(cls):
        os.environ.setdefault("QT_QPA_PLATFORM", "offscreen")
        from PySide6.QtWidgets import QApplication

        cls.app = QApplication.instance() or QApplication([])

    def setUp(self):
        self.config = load_server_config()
        self.database_name = f"pylocalinventory_client_attachments_{uuid.uuid4().hex[:12]}"
        admin = psycopg2.connect(
            host=self.config["host"], port=self.config["port"], dbname="postgres",
            user=self.config["user"], password=self.config["password"],
        )
        admin.autocommit = True
        try:
            admin.cursor().execute(f"CREATE DATABASE {self.database_name}")
        finally:
            admin.close()

        self.connection = psycopg2.connect(
            host=self.config["host"], port=self.config["port"], dbname=self.database_name,
            user=self.config["user"], password=self.config["password"],
        )
        self.cursor = self.connection.cursor()
        self.cursor.execute("""
            CREATE TABLE clients (
                id INTEGER PRIMARY KEY, name TEXT NOT NULL, username TEXT NOT NULL
            );
            CREATE TABLE sales (
                id INTEGER PRIMARY KEY, client_id INTEGER, client_username TEXT,
                devis TEXT NOT NULL, devis_number INTEGER, date TEXT, tva NUMERIC,
                created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
            );
            CREATE TABLE sales_items (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sales_id INTEGER NOT NULL, quantity NUMERIC NOT NULL, unit_price NUMERIC NOT NULL
            );
        """)
        self.cursor.execute(
            "INSERT INTO clients(id,name,username) VALUES (1,'Client A','Client A'), (2,'Client B','Client B')"
        )
        self.cursor.execute(
            "INSERT INTO sales(id,client_id,client_username,devis,date,tva) VALUES "
            "(11,1,'Client A','DE-TEST-1','2026-09-22',20), "
            "(12,NULL,'Client A','DE-TEST-2','2026-09-23',20), "
            "(21,2,'Client B','DE-TEST-B1','2026-09-24',20)"
        )
        self.cursor.execute(
            "INSERT INTO sales_items(sales_id,quantity,unit_price) VALUES "
            "(11,1,100), (12,2,100), (21,1,300)"
        )
        self.connection.commit()

        self.database = Database()
        self.database.conn = self.connection
        self.database.cursor = self.cursor
        self.database.database_name = self.database_name
        self.database.record_change = lambda *_args, **_kwargs: None
        self.service = AttachmentService(self.database)
        self.storage = tempfile.mkdtemp(prefix="pylocalinventory-client-attachments-")

    def tearDown(self):
        try:
            self.connection.close()
        finally:
            shutil.rmtree(self.storage, ignore_errors=True)
            admin = psycopg2.connect(
                host=self.config["host"], port=self.config["port"], dbname="postgres",
                user=self.config["user"], password=self.config["password"],
            )
            admin.autocommit = True
            try:
                admin.cursor().execute("SELECT pg_terminate_backend(pid) FROM pg_stat_activity WHERE datname=%s", (self.database_name,))
                admin.cursor().execute(f"DROP DATABASE IF EXISTS {self.database_name}")
            finally:
                admin.close()

    def _wait_for(self, panel):
        deadline = time.monotonic() + 8
        while time.monotonic() < deadline:
            self.app.processEvents()
            if panel._sales_thread is None and panel._fetch_thread is None:
                return
            time.sleep(0.02)
        self.fail("Attachment panel workers did not finish")

    def _open_client_attachments_dialog(self, fixture_database, client_id):
        """Mirror ClientsTab.show_attachments without user interaction."""
        from PySide6.QtCore import QTimer
        from PySide6.QtWidgets import QDialog, QVBoxLayout
        from ui.widgets.attachments_widget import AttachmentPanel

        dialog = QDialog()
        dialog.setMinimumSize(1100, 720)
        dialog.resize(1180, 780)
        layout = QVBoxLayout(dialog)
        panel = AttachmentPanel(fixture_database, "client", client_id, dialog)
        layout.addWidget(panel)
        dialog.finished.connect(panel.shutdown)
        captured = []

        def close_when_loaded():
            if panel._sales_thread is not None or panel._fetch_thread is not None:
                QTimer.singleShot(10, close_when_loaded)
                return
            captured.append((panel.client_sales_table.rowCount(), panel.table.rowCount()))
            dialog.accept()

        QTimer.singleShot(0, close_when_loaded)
        dialog.exec()
        self.app.processEvents()
        return captured[0], panel

    def _seed_attachments(self):
        pdf = base64.b64encode(b"%PDF-1.4 test").decode("ascii")
        png = base64.b64encode(b"\x89PNG\r\n\x1a\nimage").decode("ascii")
        with patch("core.attachments.storage_root", return_value=Path(self.storage)):
            general_id = self.service.upload("client", 1, "general.pdf", pdf)
            sale1_id = self.service.upload("client", 1, "sale1.pdf", pdf, sale_id=11)
            sale2_id = self.service.upload("client", 1, "sale2.jpg", png, sale_id=12)
            client_b_id = self.service.upload("client", 2, "client_b.pdf", pdf, sale_id=21)
        return pdf, general_id, sale1_id, sale2_id, client_b_id

    def test_client_panel_keeps_general_and_sale_attachments(self):
        _pdf, general_id, sale1_id, sale2_id, client_b_id = self._seed_attachments()

        records_a = self.service.list("client", 1)
        records_b = self.service.list("client", 2)
        self.assertEqual({record["id"] for record in records_a}, {general_id, sale1_id, sale2_id})
        self.assertEqual({record["sale_id"] for record in records_a}, {None, 11, 12})
        self.assertEqual({record["id"] for record in records_b}, {client_b_id})
        sales = self.database.get_client_sales(1)
        self.assertEqual([row[0] for row in sales], [12, 11])
        self.assertEqual([row[1] for row in sales], ["DE-TEST-2", "DE-TEST-1"])
        self.assertEqual([float(row[4]) for row in sales], [200.0, 100.0])
        fixture_database = SimpleNamespace(
            list_attachments=lambda *_args: records_a,
            get_client_sales=lambda *_args: sales,
            get_attachment_thumbnails_bulk=lambda *_args: {},
        )
        from ui.widgets.attachments_widget import AttachmentPanel

        panel = AttachmentPanel(fixture_database, "client", 1)
        self._wait_for(panel)
        self.assertEqual(panel.client_splitter.count(), 2)
        self.assertEqual(panel.table.maximumHeight(), 16777215)
        self.assertEqual(panel.client_sales_table.rowCount(), 2)
        self.assertEqual(panel.sale_selector.count(), 3)
        self.assertEqual(panel.table.rowCount(), 3)
        self.assertEqual({record["id"] for record in panel._shown}, {general_id, sale1_id, sale2_id})

        panel.search.setText("sale1")
        self._wait_for(panel)
        self.assertEqual([record["id"] for record in panel._shown], [sale1_id])
        panel.search.clear()
        panel.filter.setCurrentText("Images")
        self._wait_for(panel)
        self.assertEqual([record["id"] for record in panel._shown], [sale2_id])
        self.assertEqual(panel.client_sales_table.rowCount(), 2)
        panel.deleteLater()

    def test_client_dialog_reopens_and_switches_clients_without_stale_rows(self):
        pdf, _general_id, _sale1_id, _sale2_id, _client_b_id = self._seed_attachments()
        records_by_client = {
            1: self.service.list("client", 1),
            2: self.service.list("client", 2),
        }
        sales_by_client = {
            1: self.database.get_client_sales(1),
            2: self.database.get_client_sales(2),
        }
        fixture_database = SimpleNamespace(
            list_attachments=lambda _kind, client_id: records_by_client[client_id],
            get_client_sales=lambda client_id: sales_by_client[client_id],
            get_attachment_thumbnails_bulk=lambda *_args: {},
        )

        for _ in range(5):
            self.assertEqual(self._open_client_attachments_dialog(fixture_database, 1)[0], (2, 3))
        self.assertEqual(self._open_client_attachments_dialog(fixture_database, 2)[0], (1, 1))
        self.assertEqual(self._open_client_attachments_dialog(fixture_database, 1)[0], (2, 3))

        with patch("core.attachments.storage_root", return_value=Path(self.storage)):
            self.service.upload("client", 1, "new-general.pdf", pdf)
        records_by_client[1] = self.service.list("client", 1)
        self.assertEqual(self._open_client_attachments_dialog(fixture_database, 1)[0], (2, 4))

    def test_client_dialog_uses_the_rpc_data_path(self):
        _pdf, _general_id, _sale1_id, _sale2_id, _client_b_id = self._seed_attachments()
        records = self.service.list("client", 1)
        sales = self.database.get_client_sales(1)
        from core.network.client import RemoteDatabase

        remote = RemoteDatabase.__new__(RemoteDatabase)
        remote.offline = False
        remote.cache = None

        def rpc(method, args=None, kwargs=None, timeout=10):
            if method == "list_attachments":
                self.assertEqual(args, ["client", 1])
                return records
            if method == "get_client_sales":
                self.assertEqual(args, [1])
                return sales
            if method == "get_attachment_thumbnails_bulk":
                return {}
            self.fail(f"Unexpected RPC method: {method}")

        remote._call = rpc
        self.assertEqual(self._open_client_attachments_dialog(remote, 1)[0], (2, 3))
