"""Safe, metadata-only document storage shared by local and LAN clients."""
from __future__ import annotations

import base64
import logging
import mimetypes
import os
import re
import shutil
import uuid
from datetime import datetime
from pathlib import Path

from core.runtime_paths import safe_windows_component, user_data_root

logger = logging.getLogger(__name__)

ALLOWED_TYPES = {
    b"\xff\xd8\xff": ("image/jpeg", ".jpg"),
    b"\x89PNG\r\n\x1a\n": ("image/png", ".png"),
    b"RIFF": ("image/webp", ".webp"),
    b"%PDF-": ("application/pdf", ".pdf"),
}
try:
    # Host administrators can set PYLOCALINVENTORY_MAX_ATTACHMENT_MB without a
    # schema change; invalid values safely retain the conservative default.
    DEFAULT_MAX_BYTES = max(1, int(os.getenv('PYLOCALINVENTORY_MAX_ATTACHMENT_MB', '25'))) * 1024 * 1024
except ValueError:
    DEFAULT_MAX_BYTES = 25 * 1024 * 1024


def storage_root(database) -> Path:
    """Host-only root. Never expose this value to a remote caller."""
    identity = safe_windows_component(
        getattr(database, "database_name", None) or getattr(database, "schema_name", None) or "default"
    )
    root = Path(user_data_root()) / "attachments" / identity
    root.mkdir(parents=True, exist_ok=True)
    return root


def attachment_backup_root(database) -> Path:
    return storage_root(database)


def validate_bytes(data: bytes, filename: str, max_bytes=DEFAULT_MAX_BYTES):
    if not data or len(data) > int(max_bytes):
        raise ValueError(f"Attachment must be between 1 byte and {int(max_bytes) // 1024 // 1024} MB")
    kind = next(((mime, ext) for marker, (mime, ext) in ALLOWED_TYPES.items() if data.startswith(marker)), None)
    # RIFF is only WebP when its format marker is WEBP.
    if data.startswith(b"RIFF") and data[8:12] != b"WEBP":
        kind = None
    if not kind:
        raise ValueError("Only JPG, PNG, WEBP and PDF files are allowed")
    return kind


def display_filename(name: str) -> str:
    name = Path(str(name or "attachment")).name
    return re.sub(r"[\x00-\x1f<>:\\|?*]", "_", name).strip(" .")[:180] or "attachment"


class AttachmentService:
    """Database-aware attachment operations. Database rows contain no absolute paths."""
    def __init__(self, database):
        self.database = database

    def ensure_tables(self):
        cur = self.database.cursor
        # A previous UI query can leave a PostgreSQL connection aborted. Clear
        # that state before migration so opening Attachments always recovers.
        try:
            self.database.conn.rollback()
        except Exception:
            pass
        try:
            cur.execute("""
                CREATE TABLE IF NOT EXISTS attachments (
                  id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                  entity_type TEXT NOT NULL CHECK (entity_type IN ('client','sale')),
                  entity_id INTEGER NOT NULL,
                  original_filename TEXT NOT NULL,
                  display_name TEXT NOT NULL,
                  description TEXT NOT NULL DEFAULT '', category TEXT NOT NULL DEFAULT '',
                  mime_type TEXT NOT NULL, file_size BIGINT NOT NULL,
                  relative_path TEXT NOT NULL UNIQUE, created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
                  modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """)
            cur.execute("CREATE INDEX IF NOT EXISTS attachments_entity_idx ON attachments(entity_type, entity_id)")
            self.database.conn.commit()
        except Exception:
            self.database.conn.rollback()
            raise

    def _ready(self):
        self.ensure_tables()

    @staticmethod
    def _check_entity(entity_type, entity_id):
        if entity_type not in ('client', 'sale') or not isinstance(entity_id, int) or entity_id <= 0:
            raise ValueError("Invalid attachment owner")

    def list(self, entity_type, entity_id):
        self._ready()
        self._check_entity(entity_type, entity_id)
        try:
            self.database.cursor.execute(
                "SELECT id, original_filename, display_name, description, category, mime_type, file_size, relative_path, created_at, modified_at "
                "FROM attachments WHERE entity_type=%s AND entity_id=%s ORDER BY created_at DESC", (entity_type, entity_id))
            keys = ('id','original_filename','display_name','description','category','mime_type','file_size','relative_path','created_at','modified_at')
            return [dict(zip(keys, row)) for row in self.database.cursor.fetchall()]
        except Exception:
            self.database.conn.rollback()
            raise

    def upload(self, entity_type, entity_id, filename, content_b64, description='', category='', max_bytes=DEFAULT_MAX_BYTES):
        self._ready()
        self._check_entity(entity_type, entity_id)
        try:
            data = base64.b64decode(content_b64, validate=True)
        except Exception as exc:
            raise ValueError("Invalid attachment data") from exc
        mime, extension = validate_bytes(data, filename, max_bytes)
        original = display_filename(filename)
        rel = Path(entity_type) / str(entity_id) / f"{uuid.uuid4().hex}{extension}"
        target = storage_root(self.database) / rel
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(data)
        try:
            self.database.cursor.execute(
                "INSERT INTO attachments(entity_type,entity_id,original_filename,display_name,description,category,mime_type,file_size,relative_path) "
                "VALUES(%s,%s,%s,%s,%s,%s,%s,%s,%s) RETURNING id",
                (entity_type, entity_id, original, Path(original).stem, str(description or '')[:2000], str(category or '')[:100], mime, len(data), rel.as_posix()))
            attachment_id = self.database.cursor.fetchone()[0]
            self.database.conn.commit()
            self._record_change(attachment_id, 'upsert', self._snapshot(attachment_id))
            return attachment_id
        except Exception:
            self.database.conn.rollback()
            target.unlink(missing_ok=True)
            raise

    def _record(self, attachment_id):
        self._ready()
        self.database.cursor.execute("SELECT entity_type,entity_id,relative_path FROM attachments WHERE id=%s", (attachment_id,))
        row = self.database.cursor.fetchone()
        if not row:
            raise ValueError("Attachment not found")
        return row

    def _snapshot(self, attachment_id):
        """Full metadata row (no file bytes) used as the incremental-sync
        payload so clients can mirror an attachment without downloading it."""
        self._ready()
        self.database.cursor.execute(
            "SELECT id, entity_type, entity_id, original_filename, display_name, "
            "description, category, mime_type, file_size, relative_path, created_at, modified_at "
            "FROM attachments WHERE id=%s", (int(attachment_id),))
        row = self.database.cursor.fetchone()
        if row is None:
            return None
        keys = ('id', 'entity_type', 'entity_id', 'original_filename', 'display_name',
                'description', 'category', 'mime_type', 'file_size', 'relative_path',
                'created_at', 'modified_at')
        return dict(zip(keys, row))

    def _record_change(self, attachment_id, operation, payload=None):
        """Append a best-effort change-log entry so remote clients learn about
        attachment metadata changes. Never raises - sync is best-effort."""
        try:
            record = getattr(self.database, 'record_change', None)
            if record is not None:
                record('attachments', int(attachment_id), operation, payload)
        except Exception:
            logger.exception(
                "record_change failed section=attachments row_id=%s", attachment_id)

    def download(self, attachment_id):
        _kind, _entity, rel = self._record(int(attachment_id))
        path = (storage_root(self.database) / rel).resolve()
        if storage_root(self.database).resolve() not in path.parents or not path.is_file():
            raise ValueError("Attachment file is unavailable")
        return base64.b64encode(path.read_bytes()).decode('ascii')

    def thumbnail(self, attachment_id, max_size=160):
        """Return a small cached PNG thumbnail, never the original image."""
        entity_type, entity_id, rel = self._record(int(attachment_id))
        source = (storage_root(self.database) / rel).resolve()
        root = storage_root(self.database).resolve()
        if root not in source.parents or not source.is_file():
            raise ValueError("Attachment file is unavailable")
        if source.suffix.lower() not in ('.jpg', '.jpeg', '.png', '.webp'):
            return None
        # Size is part of the cache name, so existing small previews are never
        # reused after the UI asks for a larger one.
        thumbnail_path = root / '.thumbnails' / f'{int(attachment_id)}_{int(max_size)}.png'
        thumbnail_path.parent.mkdir(parents=True, exist_ok=True)
        if not thumbnail_path.exists() or thumbnail_path.stat().st_mtime < source.stat().st_mtime:
            from PySide6.QtCore import Qt
            from PySide6.QtGui import QImage
            image = QImage(str(source))
            if image.isNull():
                return None
            image = image.scaled(int(max_size), int(max_size), Qt.KeepAspectRatio, Qt.SmoothTransformation)
            if not image.save(str(thumbnail_path), 'PNG'):
                return None
        return base64.b64encode(thumbnail_path.read_bytes()).decode('ascii')

    def thumbnails(self, attachment_ids, max_size=160):
        """Bulk fetch thumbnails for multiple attachments."""
        result = {}
        for aid in attachment_ids:
            try:
                thumb = self.thumbnail(aid, max_size)
                if thumb:
                    result[aid] = thumb
            except Exception:
                pass
        return result

    def update(self, attachment_id, display_name=None, description=None, category=None):
        self._ready()
        fields, values = [], []
        for key, value, limit in (("display_name", display_name, 180), ("description", description, 2000), ("category", category, 100)):
            if value is not None:
                fields.append(f"{key}=%s"); values.append(str(value)[:limit])
        if not fields: return False
        values.append(int(attachment_id))
        self.database.cursor.execute("UPDATE attachments SET " + ", ".join(fields) + ", modified_at=CURRENT_TIMESTAMP WHERE id=%s", values)
        self.database.conn.commit()
        changed = self.database.cursor.rowcount > 0
        if changed:
            self._record_change(attachment_id, 'upsert', self._snapshot(attachment_id))
        return changed

    def delete(self, attachment_id):
        self._ready()
        _kind, _entity, rel = self._record(int(attachment_id))
        self.database.cursor.execute("DELETE FROM attachments WHERE id=%s", (attachment_id,)); self.database.conn.commit()
        self._record_change(attachment_id, 'delete', None)
        try: (storage_root(self.database) / rel).unlink(missing_ok=True)
        except OSError: pass
        try:
            for thumb in (storage_root(self.database) / '.thumbnails').glob(f'{int(attachment_id)}_*.png'):
                thumb.unlink(missing_ok=True)
        except OSError:
            pass
        return True

    def delete_owner(self, entity_type, entity_id):
        for attachment in self.list(entity_type, int(entity_id)):
            self.delete(attachment['id'])
