"""Client account view with purchases, payments, and balance tracking."""

from PySide6.QtCore import QDate, Qt
from PySide6.QtGui import QColor
from PySide6.QtWidgets import (
    QAbstractItemView,
    QDateEdit,
    QDialog,
    QFormLayout,
    QFrame,
    QHeaderView,
    QHBoxLayout,
    QLabel,
    QLineEdit,
    QMessageBox,
    QPushButton,
    QScrollArea,
    QTableWidget,
    QTableWidgetItem,
    QVBoxLayout,
    QWidget,
)
from ui.widgets.preview_widget import PreviewWidget


def _format_money(value):
    return f"{float(value or 0):,.2f}".replace(",", " ")


class ClientDetailsDialog(QDialog):
    """Show a client's account and record payments against unpaid sales."""

    def __init__(self, client_obj, database, parent=None):
        super().__init__(parent)
        self.client_obj = client_obj
        self.database = database
        self.purchases = []
        self.account_data = {"purchases": [], "payments": []}
        self.can_record_payment = bool(
            database and getattr(database, "has_permission", lambda *_: True)("Sales", "write")
        )
        self.setWindowTitle(
            f"Client Account - {client_obj.get_value('name') or client_obj.get_value('username')}"
        )
        self.setMinimumSize(1050, 720)
        # Schema changes belong to the trusted host connection, never to a
        # read-only LAN session. Database.connect() also ensures this table.
        if database.__class__.__name__ != "RemoteDatabase":
            self._ensure_payments_table()
        self._setup_ui()
        self.refresh_data()

    def _ensure_payments_table(self):
        self.database.cursor.execute(
            """
            CREATE TABLE IF NOT EXISTS Payments (
                id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                sale_id INTEGER,
                sales_item_id INTEGER,
                amount DOUBLE PRECISION,
                date TEXT,
                FOREIGN KEY (sale_id) REFERENCES Sales(id) ON DELETE CASCADE,
                FOREIGN KEY (sales_item_id) REFERENCES Sales_Items(id) ON DELETE CASCADE
            )
            """
        )
        # Avoid querying information_schema through the LAN permission layer.
        # PostgreSQL can perform this migration safely and idempotently itself.
        self.database.cursor.execute(
            "ALTER TABLE Payments ADD COLUMN IF NOT EXISTS sales_item_id INTEGER"
        )
        self.database.conn.commit()

    def _setup_ui(self):
        window_layout = QVBoxLayout(self)
        window_layout.setContentsMargins(0, 0, 0, 0)

        scroll_area = QScrollArea()
        scroll_area.setWidgetResizable(True)
        scroll_area.setHorizontalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        scroll_area.setVerticalScrollBarPolicy(Qt.ScrollBarAsNeeded)
        scroll_area.setFrameShape(QFrame.NoFrame)

        content = QWidget()
        content.setMinimumWidth(980)
        root = QVBoxLayout(content)
        root.setContentsMargins(18, 18, 18, 18)
        root.setSpacing(12)

        title = QLabel(self.client_obj.get_value("name") or "Client")
        title.setStyleSheet("font-size:22px; font-weight:bold; color:#fff;")
        root.addWidget(title)

        info = QFrame()
        info.setObjectName("clientInfo")
        info_container = QHBoxLayout(info)
        info_container.setContentsMargins(12, 10, 12, 10)
        info_container.setSpacing(16)

        preview = PreviewWidget(120, "individual")
        image_path = self.client_obj.get_value("preview_image")
        if image_path:
            preview.set_image_path(image_path)
        info_container.addWidget(preview, 0, Qt.AlignTop)

        info_fields = QWidget()
        info_layout = QFormLayout(info_fields)
        info_layout.setContentsMargins(0, 0, 0, 0)
        info_layout.setHorizontalSpacing(20)
        for label, key in (
            ("Client ID", "id"),
            ("Username", "username"),
            ("Client Type", "client_type"),
            ("ICE", "ice"),
            ("Phone", "phone"),
            ("Email", "email"),
            ("Address", "address"),
            ("Notes", "notes"),
        ):
            value = QLabel(str(self.client_obj.get_value(key) or "-"))
            value.setTextInteractionFlags(Qt.TextSelectableByMouse)
            value.setWordWrap(True)
            info_layout.addRow(f"{label}:", value)
        info_container.addWidget(info_fields, 1)
        root.addWidget(info)

        totals = QHBoxLayout()
        self.total_bought_label = self._summary_value(totals, "Total Bought")
        self.total_paid_label = self._summary_value(totals, "Total Paid")
        self.remaining_label = self._summary_value(totals, "Remaining")
        root.addLayout(totals)

        purchases_title = QLabel("Purchases")
        purchases_title.setStyleSheet("font-size:16px; font-weight:bold;")
        root.addWidget(purchases_title)

        purchase_help = QLabel(
            (
                "1. Select one product or service below.  "
                "2. Enter the amount paid manually.  "
                "3. Choose the payment date and click Add Payment."
                if self.can_record_payment
                else "Read-only view: client details, purchases, and payments cannot be changed."
            )
        )
        purchase_help.setWordWrap(True)
        purchase_help.setStyleSheet(
            "background:#19344d; color:#d9efff; border:1px solid #2878b5; "
            "border-radius:5px; padding:8px; font-weight:bold;"
        )
        root.addWidget(purchase_help)

        self.purchases_table = self._create_table(
            [
                "Sale",
                "Date",
                "Product / Service",
                "Quantity",
                "Unit Price",
                "State",
                "Total",
                "Paid",
                "Remaining",
            ]
        )
        self.purchases_table.currentCellChanged.connect(self._purchase_selected)
        self.purchases_table.setMinimumHeight(220)
        self.purchases_table.verticalHeader().setDefaultSectionSize(38)
        root.addWidget(self.purchases_table, 3)

        payments_title = QLabel("Payment History")
        payments_title.setStyleSheet("font-size:16px; font-weight:bold;")
        root.addWidget(payments_title)

        self.payments_table = self._create_table(
            ["Payment", "Sale", "Date", "Amount", "Purchase"]
        )
        root.addWidget(self.payments_table, 2)

        payment_form = QWidget()
        self.payment_form = payment_form
        form_layout = QVBoxLayout(payment_form)
        form_layout.setContentsMargins(0, 4, 0, 0)
        form_layout.setSpacing(8)

        self.selected_purchase_label = QLabel("No product or service selected")
        self.selected_purchase_label.setStyleSheet(
            "background:#3a2f1d; color:#FFD180; border:1px solid #8a6828; "
            "border-radius:5px; padding:8px; font-weight:bold;"
        )

        amount_label = QLabel("Amount Paid:")
        self.amount_input = QLineEdit()
        self.amount_input.setPlaceholderText("Type amount manually, for example 1 500.00")
        self.amount_input.setMinimumWidth(260)
        self.amount_input.setEnabled(False)

        date_label = QLabel("Operation Date:")
        self.date_input = QDateEdit(QDate.currentDate())
        self.date_input.setCalendarPopup(True)
        self.date_input.setDisplayFormat("dd-MM-yyyy")
        self.date_input.setMinimumWidth(150)

        self.add_payment_button = QPushButton("Add Payment")
        self.add_payment_button.setToolTip(
            "Record this payment for the selected product or service"
        )
        self.add_payment_button.clicked.connect(self.add_payment)

        close_button = QPushButton("Close")
        close_button.clicked.connect(self.accept)

        controls = QHBoxLayout()
        controls.addWidget(amount_label)
        controls.addWidget(self.amount_input)
        controls.addWidget(date_label)
        controls.addWidget(self.date_input)
        controls.addWidget(self.add_payment_button)
        controls.addStretch()
        controls.addWidget(close_button)

        form_layout.addWidget(self.selected_purchase_label)
        form_layout.addLayout(controls)
        root.addWidget(payment_form)
        payment_form.setVisible(self.can_record_payment)

        scroll_area.setWidget(content)
        window_layout.addWidget(scroll_area)

        self.setStyleSheet(
            """
            QDialog { background:#252525; color:#eee; }
            #clientInfo { background:#2d2d2d; border:1px solid #444; border-radius:6px; }
            QLabel { color:#eee; }
            QTableWidget {
                background:#2a2a2a; color:#eee; gridline-color:#444;
                border:1px solid #444; selection-background-color:#1565C0;
            }
            QHeaderView::section {
                background:#333; color:#fff; border:1px solid #444;
                padding:6px; font-weight:bold;
            }
            QLineEdit, QDateEdit {
                background:#333; color:#fff; border:1px solid #555;
                padding:6px; min-height:24px;
            }
            QLineEdit:focus, QDateEdit:focus { border:2px solid #2196F3; }
            QPushButton {
                background:#1565C0; color:#fff; border:none;
                border-radius:5px; padding:8px 14px;
            }
            QPushButton:hover { background:#1976D2; }
            """
        )

    def _summary_value(self, layout, title):
        block = QFrame()
        block.setObjectName("clientInfo")
        block_layout = QVBoxLayout(block)
        block_layout.setContentsMargins(12, 8, 12, 8)
        caption = QLabel(title)
        caption.setStyleSheet("color:#aaa; font-size:12px;")
        value = QLabel("0.00 MAD")
        value.setStyleSheet("font-size:18px; font-weight:bold;")
        block_layout.addWidget(caption)
        block_layout.addWidget(value)
        layout.addWidget(block)
        return value

    def _create_table(self, headers):
        table = QTableWidget(0, len(headers))
        table.setHorizontalHeaderLabels(headers)
        table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        table.setSelectionBehavior(QAbstractItemView.SelectRows)
        table.setAlternatingRowColors(True)
        table.verticalHeader().hide()
        table.horizontalHeader().setSectionResizeMode(QHeaderView.ResizeToContents)
        if len(headers) > 2:
            table.horizontalHeader().setSectionResizeMode(2, QHeaderView.Stretch)
        return table

    def _load_purchases(self):
        self.account_data = self.database.get_client_account(self.client_obj.id)
        rows = self.account_data.get("purchases", [])
        purchases = []
        for sale_id, date, state, item_id, product, quantity, unit_price, vat in rows:
            total = float(quantity or 0) * float(unit_price or 0)
            total *= 1 + float(vat or 0) / 100
            purchases.append(
                {
                    "sale_id": sale_id,
                    "item_id": item_id,
                    "date": date,
                    "state": state,
                    "product": product,
                    "quantity": quantity,
                    "unit_price": unit_price,
                    "total": total,
                    "paid": 0.0,
                    "remaining": total,
                }
            )

        targeted = {}
        legacy_by_sale = {}
        for _payment_id, sale_id, item_id, _date, amount in self.account_data.get(
            "payments", []
        ):
            if item_id is None:
                legacy_by_sale[sale_id] = legacy_by_sale.get(sale_id, 0.0) + float(
                    amount or 0
                )
            else:
                targeted[item_id] = targeted.get(item_id, 0.0) + float(amount or 0)

        for purchase in purchases:
            purchase["paid"] = min(targeted.get(purchase["item_id"], 0.0), purchase["total"])
            purchase["remaining"] = max(purchase["total"] - purchase["paid"], 0)

        # Payments created before item-level tracking are applied in item order.
        for sale_id, legacy_amount in legacy_by_sale.items():
            amount_left = legacy_amount
            for purchase in purchases:
                if purchase["sale_id"] != sale_id or amount_left <= 0:
                    continue
                allocation = min(purchase["remaining"], amount_left)
                purchase["paid"] += allocation
                purchase["remaining"] -= allocation
                amount_left -= allocation

        return purchases

    def refresh_data(self):
        self.purchases = self._load_purchases()
        self._populate_purchases()
        self._populate_payments()

        total_bought = sum(purchase["total"] for purchase in self.purchases)
        total_paid = sum(purchase["paid"] for purchase in self.purchases)
        remaining = max(total_bought - total_paid, 0)

        self.total_bought_label.setText(f"{_format_money(total_bought)} MAD")
        self.total_paid_label.setText(f"{_format_money(total_paid)} MAD")
        self.total_paid_label.setStyleSheet("font-size:18px; font-weight:bold; color:#4CAF50;")
        self.remaining_label.setText(f"{_format_money(remaining)} MAD")
        color = "#4CAF50" if remaining <= 0 else "#FF9800"
        self.remaining_label.setStyleSheet(f"font-size:18px; font-weight:bold; color:{color};")

        self.amount_input.clear()
        self.amount_input.setEnabled(False)
        self.add_payment_button.setEnabled(False)

    def _populate_purchases(self):
        self.purchases_table.setRowCount(len(self.purchases))
        for row, purchase in enumerate(self.purchases):
            values = [
                f"#{purchase['sale_id']}",
                purchase["date"],
                purchase["product"] or "-",
                str(purchase["quantity"]),
                _format_money(purchase["unit_price"]),
                str(purchase["state"]).replace("_", " ").title(),
                _format_money(purchase["total"]),
                _format_money(purchase["paid"]),
                _format_money(purchase["remaining"]),
            ]
            for col, value in enumerate(values):
                item = QTableWidgetItem(str(value))
                item.setData(Qt.UserRole, purchase["item_id"])
                item.setData(Qt.UserRole + 1, purchase["sale_id"])
                if col >= 4 and col != 5:
                    item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)
                if col == 7:
                    item.setForeground(QColor("#4CAF50"))
                elif col == 8:
                    item.setForeground(
                        QColor("#4CAF50" if purchase["remaining"] <= 0 else "#FF9800")
                    )
                self.purchases_table.setItem(row, col, item)

    def _populate_payments(self):
        rows = self.account_data.get("payments", [])
        if not rows:
            self.payments_table.setRowCount(0)
            return

        product_by_item = {
            purchase["item_id"]: purchase["product"] for purchase in self.purchases
        }
        products_by_sale = {}
        for purchase in self.purchases:
            products_by_sale.setdefault(purchase["sale_id"], []).append(
                purchase["product"]
            )
        self.payments_table.setRowCount(len(rows))
        for row_index, (payment_id, sale_id, item_id, date, amount) in enumerate(rows):
            products = product_by_item.get(item_id)
            if not products:
                products = ", ".join(
                    product for product in products_by_sale.get(sale_id, []) if product
                ) or "Sale payment"
            values = [f"#{payment_id}", f"#{sale_id}", date, _format_money(amount), products or "-"]
            for col, value in enumerate(values):
                item = QTableWidgetItem(str(value))
                if col == 3:
                    item.setTextAlignment(Qt.AlignRight | Qt.AlignVCenter)
                    item.setForeground(QColor("#4CAF50"))
                self.payments_table.setItem(row_index, col, item)

    def _purchase_selected(self, current_row, _current_col, _previous_row, _previous_col):
        if current_row < 0 or current_row >= len(self.purchases):
            self.selected_purchase_label.setText("No product or service selected")
            self.amount_input.clear()
            self.amount_input.setEnabled(False)
            self.add_payment_button.setEnabled(False)
            return

        purchase = self.purchases[current_row]
        remaining = purchase["remaining"]
        self.selected_purchase_label.setText(
            f"Selected: {purchase['product'] or 'Purchase'}  |  "
            f"Sale #{purchase['sale_id']}  |  "
            f"Remaining: {_format_money(remaining)} MAD"
        )
        if remaining <= 0:
            self.amount_input.clear()
            self.amount_input.setPlaceholderText("This item is fully paid")
            self.amount_input.setEnabled(False)
            self.add_payment_button.setEnabled(False)
            return

        self.amount_input.setEnabled(True)
        self.amount_input.clear()
        self.amount_input.setPlaceholderText(
            f"Enter up to {_format_money(remaining)} MAD"
        )
        self.amount_input.setFocus()
        self.add_payment_button.setEnabled(True)

    def add_payment(self):
        if not self.can_record_payment:
            QMessageBox.information(
                self, "Read-Only Access", "You don't have permission to record payments."
            )
            return
        selected_row = self.purchases_table.currentRow()
        if selected_row < 0 or selected_row >= len(self.purchases):
            QMessageBox.information(
                self,
                "Select Purchase",
                "Select the product or service that this payment is for.",
            )
            return

        purchase = self.purchases[selected_row]
        amount_text = self.amount_input.text().strip().replace(" ", "").replace(",", ".")
        try:
            amount = float(amount_text)
        except ValueError:
            QMessageBox.warning(
                self,
                "Invalid Amount",
                "Enter the amount manually using numbers, for example 1500 or 1500.50.",
            )
            self.amount_input.setFocus()
            return
        outstanding = purchase["remaining"]
        if outstanding <= 0:
            QMessageBox.information(
                self, "Purchase Paid", "This product or service is already fully paid."
            )
            return
        if amount <= 0 or amount > outstanding + 0.001:
            QMessageBox.warning(
                self,
                "Invalid Amount",
                f"Enter an amount between 0.01 and {_format_money(outstanding)} MAD.",
            )
            return

        date = self.date_input.date().toString("dd-MM-yyyy")
        try:
            self.database.add_client_payment(
                self.client_obj.id,
                purchase["sale_id"],
                purchase["item_id"],
                amount,
                date,
            )
        except Exception as error:
            QMessageBox.critical(self, "Payment Error", f"Could not save payment:\n{error}")
            return

        QMessageBox.information(
            self,
            "Payment Saved",
            f"Payment of {_format_money(amount)} MAD was recorded for "
            f"{purchase['product'] or 'the selected purchase'}.",
        )
        self.refresh_data()
