"""
One-time data migration: copies existing per-profile SQLite databases into the
central PostgreSQL server (one schema per profile), as part of moving this app's
storage engine off SQLite. Run manually, once per profile, after configuring
Postgres connection settings (via the Network dialog's "Database Server" tab,
or directly in profiles/_server_config.json). Never touches or deletes the
original .db files - they're left in place as a rollback fallback.

Usage:
    python -m scripts.migrate_sqlite_to_postgres --profile soufoin
    python -m scripts.migrate_sqlite_to_postgres --all
    python -m scripts.migrate_sqlite_to_postgres --all --dry-run
"""
import argparse
import os
import sqlite3
import sys

import psycopg2

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from core.database import Database
from core.pg_config import load_server_config

PROFILES_DIR = "profiles"

# FK-safe copy order. Anything not listed here (e.g. a profile-specific table
# added later) is copied afterward in whatever order sqlite_master returns it.
TABLE_ORDER = [
    'Products', 'Clients', 'Suppliers', 'Door_Types', 'Wood_Types', 'Services',
    'Sales', 'Imports',
    'Sales_Items', 'Import_Items',
    'Payments',
    'Roles', 'RolePermissions', 'Users',
    'Meta',
]

# Foreign keys the app's own table-creation code (core/database.py) adds on
# fresh installs - replicated here so cascading deletes keep working the same
# way after migration as they did before it.
FK_CLAUSES = {
    'Sales_Items': "FOREIGN KEY (sales_id) REFERENCES sales(id) ON DELETE CASCADE",
    'Import_Items': "FOREIGN KEY (import_id) REFERENCES imports(id) ON DELETE CASCADE",
}

# Table-level UNIQUE constraints core/database.py's _ensure_user_tables() adds
# on fresh installs - PRAGMA table_info only reports per-column info, so these
# don't come across automatically. core/user_manager.py's set_role_permission()
# relies on the RolePermissions one via ON CONFLICT(role_id, section).
UNIQUE_CLAUSES = {
    'Roles': "UNIQUE (name)",
    'Users': "UNIQUE (username)",
    'RolePermissions': "UNIQUE (role_id, section)",
}

# Column renames needed because the app's schema changed since these SQLite
# databases were created - classes/reports_class.py used to use capitalized
# parameter keys ("Department"/"Date"/"Report"), which is what got stored as
# the actual column names; the app now uses lowercase everywhere.
COLUMN_RENAMES = {
    'Reports': {'Department': 'department', 'Date': 'date', 'Report': 'report'},
}

# Column type overrides, by target column name, regardless of table: the
# source SQLite column's own declared type isn't trustworthy here. 'tva' is
# declared TEXT in the old schema (Sales/Imports 'tva' parameter type is
# 'bool', which core/database.py's old type-mapping put into TEXT) even
# though it always holds a numeric percentage (20.0/0.0) - raw SQL elsewhere
# does arithmetic on it (`s.tva/100`), which requires a real numeric column.
COLUMN_TYPE_OVERRIDES = {
    'tva': 'DOUBLE PRECISION',
}

SQLITE_TO_PG_TYPE = {
    'INTEGER': 'INTEGER',
    'REAL': 'DOUBLE PRECISION',
    'TEXT': 'TEXT',
}


def _pg_type(sqlite_type):
    return SQLITE_TO_PG_TYPE.get((sqlite_type or '').upper(), 'TEXT')


def discover_sqlite_tables(sconn):
    cur = sconn.cursor()
    cur.execute("SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%'")
    return [r[0] for r in cur.fetchall()]


def ordered_tables(tables):
    ordered = [t for t in TABLE_ORDER if t in tables]
    ordered += [t for t in tables if t not in TABLE_ORDER]
    return ordered


def migrate_table(sconn, pcur, table):
    """Copy one table's structure + rows from the sqlite connection into the
    already-selected Postgres schema (search_path set by the caller)."""
    scur = sconn.cursor()
    scur.execute(f"PRAGMA table_info({table})")
    columns_info = scur.fetchall()  # (cid, name, type, notnull, dflt_value, pk)
    if not columns_info:
        print(f"  - {table}: not found in source, skipping")
        return

    rename_map = COLUMN_RENAMES.get(table, {})
    pg_table = table.lower()

    source_col_names = []
    target_col_names = []
    col_defs = []
    for _cid, name, sqlite_type, _notnull, _dflt, pk in columns_info:
        source_col_names.append(name)
        if pk and (sqlite_type or '').upper() == 'INTEGER':
            # Auto-incrementing integer PK (the common case - ID/AUTOINCREMENT)
            target_col_names.append('id')
            col_defs.append('id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY')
        else:
            target_name = rename_map.get(name, name).lower()
            target_col_names.append(target_name)
            pg_type = COLUMN_TYPE_OVERRIDES.get(target_name) or _pg_type(sqlite_type)
            col_defs.append(f"{target_name} {pg_type} PRIMARY KEY" if pk else f"{target_name} {pg_type}")

    if table in FK_CLAUSES:
        col_defs.append(FK_CLAUSES[table])
    if table in UNIQUE_CLAUSES:
        col_defs.append(UNIQUE_CLAUSES[table])

    pcur.execute(f"CREATE TABLE IF NOT EXISTS {pg_table} ({', '.join(col_defs)})")

    quoted_source_cols = ", ".join(f'"{c}"' for c in source_col_names)
    scur.execute(f"SELECT {quoted_source_cols} FROM {table}")
    rows = scur.fetchall()
    if not rows:
        print(f"  - {table}: 0 rows")
        return

    placeholders = ", ".join(["%s"] * len(target_col_names))
    insert_sql = f"INSERT INTO {pg_table} ({', '.join(target_col_names)}) VALUES ({placeholders})"
    for row in rows:
        pcur.execute(insert_sql, row)

    if 'id' in target_col_names:
        pcur.execute(f"SELECT MAX(id) FROM {pg_table}")
        max_id = pcur.fetchone()[0]
        if max_id is not None:
            pcur.execute("SELECT setval(pg_get_serial_sequence(%s, 'id'), %s)", (pg_table, max_id))

    print(f"  OK {table} -> {pg_table}: {len(rows)} rows")


def migrate_profile(profile_name, dry_run=False):
    db_path = os.path.join(PROFILES_DIR, profile_name, f"{profile_name}.db")
    if not os.path.exists(db_path):
        print(f"Skipping '{profile_name}': no {db_path} found")
        return

    schema_name = Database._sanitize_schema_name(profile_name)
    print(f"\n=== Migrating profile '{profile_name}' -> schema '{schema_name}' ===")

    sconn = sqlite3.connect(f"file:{db_path}?mode=ro", uri=True)
    pg_config = load_server_config()
    pconn = psycopg2.connect(
        host=pg_config.get('host'), port=pg_config.get('port'),
        dbname=pg_config.get('database'), user=pg_config.get('user'),
        password=pg_config.get('password'),
    )
    pcur = pconn.cursor()

    try:
        pcur.execute(f"CREATE SCHEMA IF NOT EXISTS {schema_name}")
        pcur.execute(f"SET search_path TO {schema_name}")

        tables = ordered_tables(discover_sqlite_tables(sconn))
        for table in tables:
            migrate_table(sconn, pcur, table)

        if dry_run:
            pconn.rollback()
            print(f"(dry run - no changes committed for '{profile_name}')")
        else:
            pconn.commit()
            print(f"Migration committed for '{profile_name}'")
    except Exception:
        pconn.rollback()
        raise
    finally:
        sconn.close()
        pconn.close()


def main():
    parser = argparse.ArgumentParser(
        description="Migrate profile SQLite databases into the central Postgres server."
    )
    parser.add_argument('--profile', help="Name of a single profile to migrate")
    parser.add_argument('--all', action='store_true', help="Migrate every profile under profiles/")
    parser.add_argument('--dry-run', action='store_true', help="Do everything except commit")
    args = parser.parse_args()

    if not args.profile and not args.all:
        parser.error("Specify --profile <name> or --all")

    if args.all:
        profiles = [
            d for d in os.listdir(PROFILES_DIR)
            if os.path.isdir(os.path.join(PROFILES_DIR, d)) and d != 'deleted'
        ]
    else:
        profiles = [args.profile]

    for profile_name in profiles:
        migrate_profile(profile_name, dry_run=args.dry_run)


if __name__ == '__main__':
    main()
